export interface MenuItem {
  id: number;
  name: string;
  link: string;
  mothercat: boolean;
  icon: string; // نام آیکون در فرمت PascalCase (مثل "Build", "Power")
  subcat: {
    id: number;
    name: string;
    items: { id: number; name: string }[];
  }[];
}

export const megamenu: MenuItem[] = [
  {
    id: 1,
    name: "ابزار دستی",
    link: "hand-tools",
    mothercat: true,
    icon: "Build",
    subcat: [
      {
        id: 1,
        name: "آچار و پیچ‌گوشتی",
        items: [
          { id: 1, name: "آچار فرانسه" },
          { id: 2, name: "آچار شلاقی" },
        ],
      },
      {
        id: 2,
        name: "انبر و قیچی",
        items: [
          { id: 1, name: "انبر کلاغی" },
          { id: 2, name: "قیچی ورق‌بر" },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "ابزار برقی",
    link: "power-tools",
    mothercat: true,
    icon: "Power",
    subcat: [
      {
        id: 1,
        name: "دریل و پیچ‌گوشتی برقی",
        items: [
          { id: 1, name: "دریل شارژی" },
          { id: 2, name: "دریل برقی" },
        ],
      },
      {
        id: 2,
        name: "اره برقی",
        items: [
          { id: 1, name: "اره زنجیری" },
          { id: 2, name: "اره گردبر" },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "تجهیزات صنعتی",
    link: "industrial-equipment",
    mothercat: true,
    icon: "Factory",
    subcat: [
      {
        id: 1,
        name: "جوشکاری",
        items: [
          { id: 1, name: "دستگاه جوش اینورتر" },
          { id: 2, name: "الکترود جوشکاری" },
        ],
      },
      {
        id: 2,
        name: "کمپرسور هوا",
        items: [
          { id: 1, name: "کمپرسور تک‌فاز" },
          { id: 2, name: "کمپرسور سه‌فاز" },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "ابزار باغبانی",
    link: "gardening-tools",
    mothercat: true,
    icon: "Yard",
    subcat: [
      {
        id: 1,
        name: "ابزار هرس",
        items: [
          { id: 1, name: "قیچی هرس" },
          { id: 2, name: "اره هرس" },
        ],
      },
      {
        id: 2,
        name: "ابزار خاک‌ورزی",
        items: [
          { id: 1, name: "بیلچه باغبانی" },
          { id: 2, name: "شن‌کش" },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "تجهیزات ایمنی",
    link: "safety-equipment",
    mothercat: true,
    icon: "Security",
    subcat: [
      {
        id: 1,
        name: "تجهیزات حفاظت فردی",
        items: [
          { id: 1, name: "کلاه ایمنی" },
          { id: 2, name: "دستکش کار" },
        ],
      },
      {
        id: 2,
        name: "تجهیزات ایمنی محیط",
        items: [
          { id: 1, name: "کپسول آتش‌نشانی" },
          { id: 2, name: "تابلو هشدار" },
        ],
      },
    ],
  },
];


interface MediaItem {
  type: 'image' | 'video';
  src: string;
  thumbnail: string;
  alt: string;
}

interface Product {
  id: number;
  title: string;
  mothercat?: string;
  subcat?: string;
  features?: string[];
  content?: string;
  brand: string;
  originalPrice: string;
  discountedPrice: string;
  wholesalePrice: string;
  discountwholesalePrice: string;
  minwholesale: number;
  discount: string;
  discountwholesale: string;
  media?: MediaItem[];
  category: string;
  image?: string;
  rating: number;
  inStock: boolean;
  numericPrice: number;
}



 export const products: Product[] = [
    {
      id: 1,
      brand: "پیکسل",
      title: "ضد آفتاب بدون رنگ مناسب پوست های جوش دار و چرب حجم 50 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/5666500020-202491110947692.jpg?w=104",
      originalPrice: "479,000",
      discountedPrice: "431,100",
      wholesalePrice: "400,000",
      discountwholesalePrice: "340,000",
      minwholesale: 2,
      discount: "10%",
      discountwholesale: "15%",
      category: "مراقبت پوست",
      rating: 3.5,
      inStock: true,
      numericPrice: 431100,
    },
    {
      id: 2,
      brand: "مورینگا",
      title: "سرم ضد چروک صورت حجم 55 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/49631-2024619172532356.jpg?w=104",
      originalPrice: "389,400",
      discountedPrice: "298,900",
      wholesalePrice: "270,000",
      discountwholesalePrice: "229,500",
      discount: "23%",
      minwholesale: 6,
      discountwholesale: "15%",
      category: "مراقبت پوست",
      rating: 4.0,
      inStock: true,
      numericPrice: 298900,
    },
    {
      id: 3,
      brand: "پرایم",
      title: "کرم مرطوب کننده 24 ساعته",
      image: "https://storage.khanoumi.com/ProductImages/00-2024415162411605.jpg?w=104",
      originalPrice: "597,000",
      discountedPrice: "537,300",
      wholesalePrice: "500,000",
      discountwholesalePrice: "450,000",
      minwholesale: 2,
      discount: "10%",
      discountwholesale: "10%",
      category: "مراقبت پوست",
      rating: 4.2,
      inStock: true,
      numericPrice: 537300,
    },
    {
      id: 4,
      brand: "لافارر",
      title: "ژل شستشو صورت مدل لایه بردار شماره 1 مناسب پوست چرب و مستعد آکنه حجم 150 میلی لیت",
      image: "https://storage.khanoumi.com/ProductImages/ییث-2024123184526759.jpg?w=104",
      originalPrice: "631,900",
      discountedPrice: "568,710",
      wholesalePrice: "530,000",
      discountwholesalePrice: "450,500",
      minwholesale: 2,
      discount: "10%",
      discountwholesale: "15%",
      category: "مراقبت پوست",
      rating: 4.3,
      inStock: false,
      numericPrice: 568710,
    },
    {
      id: 5,
      brand: "تکنو درای",
      title: "سشوار حرفه ای مدل Tornado 6000",
      image: "https://storage.khanoumi.com/ProductImages/82911-2024122215532624.jpg?w=104",
      originalPrice: "4,510,000",
      discountedPrice: "4,370,000",
      wholesalePrice: "4,100,000",
      discountwholesalePrice: "3,280,000",
      minwholesale: 2,
      discount: "3%",
      discountwholesale: "20%",
      category: "مراقبت مو",
      rating: 4.5,
      inStock: true,
      numericPrice: 4370000,
    },
    {
      id: 6,
      brand: "دیفکتو",
      title: "ژل ابرو ژلی کاسه ای 25ml",
      image: "https://storage.khanoumi.com/ProductImages/71279-2025414155838450.jpg?w=104",
      originalPrice: "177,000",
      discountedPrice: "123,900",
      wholesalePrice: "110,000",
      discountwholesalePrice: "99,000",
      minwholesale: 2,
      discount: "30%",
      discountwholesale: "10%",
      category: "مراقبت مو",
      rating: 3.8,
      inStock: true,
      numericPrice: 123900,
    },
    {
      id: 7,
      brand: "کلاژینو",
      title: "ساشه Collagen Beauty بسته 30 عددی",
      image: "https://storage.khanoumi.com/ProductImages/77211-2025414161656479.jpg?w=104",
      originalPrice: "1,081,800",
      discountedPrice: "749,000",
      wholesalePrice: "700,000",
      discountwholesalePrice: "560,000",
      minwholesale: 2,
      discount: "31%",
      discountwholesale: "20%",
      category: "مراقبت پوست",
      rating: 4.1,
      inStock: true,
      numericPrice: 749000,
    },
    {
      id: 8,
      brand: "تاپ شاپ",
      title: "ماسک مو با آب کشی حاوی روغن آرگان حجم 500 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/DSC00012-202469163231910.jpg?w=104",
      originalPrice: "557,900",
      discountedPrice: "502,110",
      wholesalePrice: "470,000",
      discountwholesalePrice: "423,000",
      minwholesale: 2,
      discount: "10%",
      discountwholesale: "10%",
      category: "مراقبت مو",
      rating: 4.0,
      inStock: false,
      numericPrice: 502110,
    },
    {
      id: 9,
      brand: "هات لاو",
      title: "ادو پرفیوم زنانه مدل Victoria Secret Bombshell حجم 100 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/Birsen-3P-Retinol-Serum-30-ml-2024115141356583.jpg?w=130",
      originalPrice: "990,000",
      discountedPrice: "689,000",
      wholesalePrice: "650,000",
      discountwholesalePrice: "520,000",
      minwholesale: 2,
      discount: "30%",
      discountwholesale: "20%",
      category: "عطر و ادکلن",
      rating: 4.4,
      inStock: true,
      numericPrice: 689000,
    },
    {
      id: 10,
      brand: "نیوآ",
      title: "کرم ضد آفتاب SPF 50+ حجم 50 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/LSNL100006-2024622124819951.jpg?w=130",
      originalPrice: "250,000",
      discountedPrice: "200,000",
      wholesalePrice: "180,000",
      discountwholesalePrice: "171,000",
      minwholesale: 4,
      discount: "20%",
      discountwholesale: "5%",
      category: "مراقبت پوست",
      rating: 4.2,
      inStock: true,
      numericPrice: 200000,
    },
    {
      id: 11,
      brand: "گارنیر",
      title: "شامپو تقویت کننده موهای ضعیف حجم 400 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/06c20775369143469e025270cb4c8c91.jpg?w=130",
      originalPrice: "180,000",
      discountedPrice: "144,000",
      wholesalePrice: "130,000",
      discountwholesalePrice: "123,500",
      minwholesale: 3,
      discount: "20%",
      discountwholesale: "5%",
      category: "مراقبت مو",
      rating: 3.9,
      inStock: true,
      numericPrice: 144000,
    },
    {
      id: 12,
      brand: "لورآل",
      title: "رژ لب مات سری Rouge Signature",
      image: "https://storage.khanoumi.com/ProductImages/36317-(2)-2024818154254290.jpg?w=130",
      originalPrice: "350,000",
      discountedPrice: "280,000",
      wholesalePrice: "260,000",
      discountwholesalePrice: "221,000",
      minwholesale: 3,
      discount: "20%",
      discountwholesale: "15%",
      category: "آرایشی",
      rating: 4.5,
      inStock: true,
      numericPrice: 280000,
    },
    {
      id: 13,
      brand: "میبلین",
      title: "ریمل حجم دهنده Lash Sensational",
      image: "https://storage.khanoumi.com/ProductImages/_DSC9896-202553145317830.jpg?w=130",
      originalPrice: "290,000",
      discountedPrice: "232,000",
      wholesalePrice: "210,000",
      discountwholesalePrice: "178,500",
      minwholesale: 4,
      discount: "20%",
      discountwholesale: "15%",
      category: "آرایشی",
      rating: 4.3,
      inStock: false,
      numericPrice: 232000,
    },
    {
      id: 14,
      brand: "اوریف لیم",
      title: "عطر مردانه Eclat Homme حجم 75 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/1-2025423161754498.jpg?w=130",
      originalPrice: "1,200,000",
      discountedPrice: "960,000",
      wholesalePrice: "900,000",
      discountwholesalePrice: "675,000",
      minwholesale: 5,
      discount: "20%",
      discountwholesale: "25%",
      category: "عطر و ادکلن",
      rating: 4.6,
      inStock: true,
      numericPrice: 960000,
    },
    {
      id: 15,
      brand: "سفورا",
      title: "پالت سایه چشم Urban Decay Naked3",
      image: "https://storage.khanoumi.com/ProductImages/8202400005-20241020143719448.jpg?w=130",
      originalPrice: "2,500,000",
      discountedPrice: "2,000,000",
      wholesalePrice: "1,850,000",
      discountwholesalePrice: "1,387,500",
      minwholesale: 2,
      discount: "20%",
      discountwholesale: "25%",
      category: "آرایشی",
      rating: 4.7,
      inStock: true,
      numericPrice: 2000000,
    },
    {
      id: 16,
      brand: "دکتر ژیلا",
      title: "کرم دور چشم ضد چروک حجم 20 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/1-20241211974877.jpg?w=130",
      originalPrice: "320,000",
      discountedPrice: "256,000",
      wholesalePrice: "240,000",
      discountwholesalePrice: "216,000",
      minwholesale: 2,
      discount: "20%",
      discountwholesale: "10%",
      category: "مراقبت پوست",
      rating: 4.0,
      inStock: true,
      numericPrice: 256000,
    },
    {
      id: 17,
      brand: "پنتن",
      title: "شامپو ضد ریزش مو حجم 350 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/1-20241211974877.jpg?w=130",
      originalPrice: "150,000",
      discountedPrice: "120,000",
      wholesalePrice: "110,000",
      discountwholesalePrice: "99,000",
      minwholesale: 2,
      discount: "20%",
      discountwholesale: "10%",
      category: "مراقبت مو",
      rating: 3.8,
      inStock: true,
      numericPrice: 120000,
    },
    {
      id: 18,
      brand: "رولون",
      title: "لاک ناخن سری ColorStay",
      image: "https://storage.khanoumi.com/ProductImages/76350-2024810143222929.jpg?w=130",
      originalPrice: "200,000",
      discountedPrice: "160,000",
      wholesalePrice: "150,000",
      discountwholesalePrice: "142,500",
      minwholesale: 2,
      discount: "20%",
      discountwholesale: "5%",
      category: "آرایشی",
      rating: 4.1,
      inStock: true,
      numericPrice: 160000,
    },
    {
      id: 19,
      brand: "کرید",
      title: "عطر Aventus حجم 100 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/DSC00012-202469163231910.jpg?w=130",
      originalPrice: "3,800,000",
      discountedPrice: "3,040,000",
      wholesalePrice: "2,800,000",
      discountwholesalePrice: "2,100,000",
      minwholesale: 2,
      discount: "20%",
      discountwholesale: "25%",
      category: "عطر و ادکلن",
      rating: 4.8,
      inStock: true,
      numericPrice: 3040000,
    },
    {
      id: 20,
      brand: "بیودرما",
      title: "میسلار واتر پاک کننده آرایش حجم 250 میلی لیتر",
      image: "https://storage.khanoumi.com/ProductImages/5666500020-202491110947692.jpg?w=130",
      originalPrice: "450,000",
      discountedPrice: "360,000",
      wholesalePrice: "330,000",
      discountwholesalePrice: "297,000",
      minwholesale: 2,
      discount: "20%",
      discountwholesale: "10%",
      category: "مراقبت پوست",
      rating: 4.3,
      inStock: true,
      numericPrice: 360000,
    },
  ];