import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { CartProvider } from "@/ContextApi/CartContext";
import WideHeaderContainer from "@/Components/Header/WideHeader/WideHeaderContainer";
import FooterContainer from "@/Components/Footer/FooterContainer";
import MobileBottomNavigation from "@/Components/Header/MobileHeader/MobileBottomNavigation";
import MoblieHeaderTopTab from "@/Components/Header/MobileHeader/MoblieHeaderTopTab";
import { AuthProvider } from "@/ContextApi/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body >
        <AuthProvider>
          
        <CartProvider>
          <WideHeaderContainer />
          <MoblieHeaderTopTab />
          {children}
          <FooterContainer />
          <MobileBottomNavigation />
        </CartProvider>
        
        </AuthProvider>
      </body>
    </html>
  );
}
